<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="brmodel" nsURI="http://atlanmod.org/brmodel.ecore" nsPrefix="brmodel">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//Rule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slicedVariable" lowerBound="1"
        eType="#//SlicedVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ruleParts" upperBound="-1"
        eType="#//RulePart" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RulePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedMethod" eType="#//RelatedMethod"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="granularity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedStatements" upperBound="-1"
        eType="#//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reachableMethods" upperBound="-1"
        eType="#//ReachableMethod" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedVariables" upperBound="-1"
        eType="#//ReachableVariable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelatedMethod" eSuperTypes="#//Method"/>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" eSuperTypes="#//Trace">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textContent" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SlicedVariable" eSuperTypes="#//Variable"/>
  <eClassifiers xsi:type="ecore:EClass" name="RelatedVariable" eSuperTypes="#//Variable"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReachableVariable" eSuperTypes="#//Variable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" abstract="true" eSuperTypes="#//Trace">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkToCode" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method" abstract="true" eSuperTypes="#//Trace">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="class" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReachableMethod" eSuperTypes="#//Method">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
